export type UserProviders = "GOOGLE" | "LOCAL";
export type AddressType = {
  _id?: string; // generated by MongoDB
  full_name: string;
  phone: string;
  country: string; // default: "Egypt"
  city: string;
  area: string;
  address_line_1: string;
  address_line_2?: string;
  building_number?: string;
  floor?: string;
  apartment?: string;
  postal_code?: string;
  notes?: string;
  is_default?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};
export interface UserType {
  _id: string;
  activationToken?: string;
  birthDate?: Date;
  createdAt: Date;
  email: string;
  gender?: "FEMALE" | "MALE";
  imageUrl?: string;
  name: string;
  password: string;
  phone?: string;
  provider: UserProviders;
  status: "ACTIVE" | "INACTIVE";
  lastlogin?: Date;
  passwordResetToken?: string;
  passwordResetExpires?: Date;
  passwordChangedAt?: Date;
  isAdmin?: Boolean;
  addresses?: AddressType[];
}

export interface UserInfoDto {
  _id: string;
  activationToken?: string;
  birthDate?: Date;
  createdAt: Date;
  email: string;
  gender?: "FEMALE" | "MALE";
  imageUrl?: string;
  name: string;
  password: string;
  phone?: string;
  provider: UserProviders;
  status: "ACTIVE" | "INACTIVE";
  lastlogin?: Date;
  passwordResetToken?: string;
  passwordResetExpires?: Date;
  passwordChangedAt?: Date;
  isAdmin: Boolean;
  addresses: AddressType[];
}
