export const CITIES = [
  { nameAr: "الإسكندرية", nameEn: "Alexandria" },
  { nameAr: "الإسماعيلية", nameEn: "Ismailia" },
  { nameAr: "أسوان", nameEn: "Aswan" },
  { nameAr: "أسيوط", nameEn: "Assiut" },
  { nameAr: "الأقصر", nameEn: "Luxor" },
  { nameAr: "البحر الأحمر", nameEn: "Red Sea" },
  { nameAr: "البحيرة", nameEn: "Beheira" },
  { nameAr: "بني سويف", nameEn: "Beni Suef" },
  { nameAr: "بورسعيد", nameEn: "Port Said" },
  { nameAr: "جنوب سيناء", nameEn: "South Sinai" },
  { nameAr: "الجيزة", nameEn: "Giza" },
  { nameAr: "الدقهلية", nameEn: "Dakahlia" },
  { nameAr: "دمياط", nameEn: "Damietta" },
  { nameAr: "سوهاج", nameEn: "Sohag" },
  { nameAr: "السويس", nameEn: "Suez" },
  { nameAr: "الشرقية", nameEn: "Sharqia" },
  { nameAr: "شمال سيناء", nameEn: "North Sinai" },
  { nameAr: "الغربية", nameEn: "Gharbia" },
  { nameAr: "الفيوم", nameEn: "Fayoum" },
  { nameAr: "القاهرة", nameEn: "Cairo" },
  { nameAr: "القليوبية", nameEn: "Qalyubia" },
  { nameAr: "قنا", nameEn: "Qena" },
  { nameAr: "كفر الشيخ", nameEn: "Kafr El Sheikh" },
  { nameAr: "مطروح", nameEn: "Matrouh" },
  { nameAr: "المنوفية", nameEn: "Monufia" },
  { nameAr: "المنيا", nameEn: "Minya" },
  { nameAr: "الوادي الجديد", nameEn: "New Valley" },
];
